joelittlejohn/jsonschema2pojo

pom.xml

Upgraded the javadoc plugin to 2.10.1 to resolve warnings.

Resolves warnings for 'cannot find symbol' in CLI package.

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/TypeRule.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/TypeRuleTest.java

This PR adds support for the `javaType` on `integer` and `number` properties.
`integer` supports the following `javaType` values:
-  `int`
- `java.lang.Integer`
- `long`
- `java.lang.Long`
`number` supports the following `javaType` values:
- `float`
- `java.lang.Float`
- `double`
- `java.lang.Double`
When `javaType` is present, the configuration settings are ignored.

Added support for javaType on integer and number properties.

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Jackson1Annotator.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Jackson2Annotator.java
jsonschema2pojo-integration-tests/src/test/java/com/example/MyJsonViewClass.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/ViewIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/views/views.json

Hi,
I have a need to use jackson's JsonView annotation with your wonderful library. Here is the change I made to make use of that feature. It adds handling of the "javaJsonView" field name to the schema json. This causes a @JsonView annotation to appear on the resulting field of the pojo.
cheers,
Jon
(this was previously https://github.com/joelittlejohn/jsonschema2pojo/pull/290)

Add support for Jackson's JsonView

---

jsonschema2pojo-ant/pom.xml
jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
jsonschema2pojo-cli/pom.xml
jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Jsonschema2PojoCLI.java
jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/UrlConverter.java
jsonschema2pojo-cli/src/test/java/org/jsonschema2pojo/cli/ArgumentsTest.java
jsonschema2pojo-cli/src/test/java/org/jsonschema2pojo/cli/UrlConverterTest.java
jsonschema2pojo-core/pom.xml
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/DefaultGenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Jsonschema2Pojo.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/URLProtocol.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/URLUtil.java
jsonschema2pojo-gradle-plugin/pom.xml
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy
jsonschema2pojo-integration-tests/pom.xml
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/RegressionIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/util/CodeGenerationHelper.java
jsonschema2pojo-maven-plugin/pom.xml
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java
jsonschema2pojo-maven-plugin/src/test/java/org/jsonschema2pojo/maven/MatchPatternsFileFilterTest.java
pom.xml

This PR was made to implement enhancement described in https://github.com/joelittlejohn/jsonschema2pojo/issues/293

Accept url sources

---

jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/DefaultGenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/DefaultRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/FormatRule.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/FormatRuleJodaTest.java
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/DefaultIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/JodaDatesIT.java
jsonschema2pojo-integration-tests/src/test/resources/ant/build.xml
jsonschema2pojo-integration-tests/src/test/resources/schema/default/default.json
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java

https://github.com/joelittlejohn/jsonschema2pojo/issues/298
I'm pretty sure I covered everything here. I added 2 new config flags - useJodaLocalDates and useJodaLocalTimes. If those are set to true, and the schema is type string with format date or format time, the generated class properties will have types of LocalDate and LocalTime, respectively.
I've run the integration tests, and manually packaged a test version, using the maven plugin in my application to use this version, and verified that the class gets generated correctly.

Added options to generate Joda LocalDate and LocalTime for date and time formatted strings

---

jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/filtering/FilteringIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/util/CodeGenerationHelper.java
jsonschema2pojo-integration-tests/src/test/resources/schema/filtering/.svn/svn.json
jsonschema2pojo-integration-tests/src/test/resources/schema/filtering/sub/.svn/sub.json
jsonschema2pojo-integration-tests/src/test/resources/schema/filtering/sub/sub.json
jsonschema2pojo-integration-tests/src/test/resources/schema/filtering/sub/sub2/.svn/sub.json
jsonschema2pojo-integration-tests/src/test/resources/schema/filtering/sub/sub2/sub.json
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/MatchPatternsFileFilter.java
jsonschema2pojo-maven-plugin/src/test/java/org/jsonschema2pojo/maven/MatchPatternsFileFilterTest.java
jsonschema2pojo-maven-plugin/src/test/resources/filtered/schema/.svn/sub/sub-svn-file.json
jsonschema2pojo-maven-plugin/src/test/resources/filtered/schema/.svn/svn-file.json

The default set of exclude directories was causing all files to be excluded.  This corrects that issue and adds tests related to the default exclude list.  This is related to #332.
This PR also adds the default set of maven excludes anytime the sourceDirectory property is supplied without the sourcePaths property.

Corrected Exclude Pattern Behavior with Maven.

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Jsonschema2Pojo.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/EmptyPackageNameIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/emptyPackageName/levelOne/levelOneType.json
jsonschema2pojo-integration-tests/src/test/resources/schema/emptyPackageName/levelOne/levelTwo/levelTwoType.json
jsonschema2pojo-integration-tests/src/test/resources/schema/emptyPackageName/levelZeroType.json

This PR corrects an issue where the `targetPackage` is empty and source files were being generated with a `package .;` statement.
This update has the following known limitation:  If the source directory contains a directory that is a java keyword, like `/default`, then the generated source will be invalid.  Not sure if handling key words should be part of this PR or another.

Allow empty package names

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/EnumRule.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/EnumRuleTest.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/EnumIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/enum/multipleEnumArraysWithSameName.json

The following Json causes JClassAlreadyExistsException
```javascript
{
"type": "object",
"foo": {
"type": "object",
"statuses": {
"type": "array",
"items": {
"type": "string",
"enum": [
"open",
"closed"
]
}
}
}
},
"bar": {
"type": "object",
"statuses": {
"type": "array",
"items": {
"type": "string",
"enum": [
"open",
"closed"
]
}
}
}
}
}
}
```
In this case, as the enum item is inside arrays, the enum class is generated at the package level. If there are multiple enum properties with same name, there is a name collision. Changed the EnumRule code to append _ to the Enum name, if a class by that name is already found.

Multiple enum array properties with same name cause JClassAlreadyExistsException

---

jsonschema2pojo-gradle-plugin/example/android/app/build.gradle
jsonschema2pojo-gradle-plugin/example/android/lib/build.gradle
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/GenerateJsonSchemaTask.groovy

I couldn't get my library project to build.  The issue was the plugin was calling android.applicationVariants always.  For library projects it should be android.libraryVariants.

Jophde fix lib projects

---

jsonschema2pojo-cli/src/main/scripts/jsonschema2pojo.bat

Hi guys, I've run windows cli jsonschema2pojo.bat cli and it failed with error saying jar file is not found. Problem was that I've run the script not from jsonschema2pojo home, but from my own folder, and path to the jsonschema2pojo jar in the script is relative to jsonschema2pojo home.
Here's fix for the issue. I've changed relative path to the jar to absolute path, so now the windows cli runner works fine not just from jsonschema2pojo home.

Fix path to jar in windows script for the case it is run not from home dir

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/TypeRule.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/TypeRuleTest.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/TypeIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/type/integerWithLongMaximumAsLong.json
jsonschema2pojo-integration-tests/src/test/resources/schema/type/integerWithLongMinimumAsLong.json

Use the minimum and maximum properties as a hint to the java type of an integer.
Given the simple json object below we can infer that the type will be a long because the minimum value is to small.
```
{
"type" : "object",
"properties" : {
"longProperty" : {
"type" : "integer",
"minimum": -2147483649
}
}
}
```
resolves #375

Use minimum and maximum value of an integer property to determine java type long

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/Inflector.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/util/InflectorTest.java

- reduced public API to 2 synchronized methods: singularize/pluralize
- eagerly construct singleton to avoid construction race
- remove unnecessary static lists/methods
(encountering sporadic failures from a parallel Maven build using RAML JAXRS Codegen Maven plugin)

Make Inflector more amenable to thread safety.

---

jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/DefaultGenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/LanguageFeatures.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/Models.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/ParcelableHelper.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/util/LanguageFeaturesTest.java
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/ant/Jsonschema2PojoTaskIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/util/CodeGenerationHelper.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/util/Compiler.java
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java
pom.xml

Exposes a `targetVersion` property to the rules and test compiler, specifying the target Java version to generate for.
This fixes an issue during cross compilation where the source generated is valid for the JVM running the test suite but not for the JVM being targeted.  For instance, auto boxing a cast like `(int)value` works in `Java7` but not in `Java6`.
__Interface Changes__:
- Maven: adds a `targetVersion` config property, with a default value of `maven.compiler.target`.
- Gradle: adds a `targetVersion` property, with a default value of `1.6`
- Ant: adds a `targetVersion` property, with a default value of `1.6`
- CLI: adds options `-tv` and `--target-version`, with a default value of `1.6`
__Limitations__:  This patch does not set the bootclasspath from `toolchains.xml`.  So, there …

Specify target JVM version

---

jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/DefaultGenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Schema.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/SchemaStore.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/FormatRule.java
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/CustomDatesIT.java
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java

Tidying up and replacing #433.

Added support for custom date-time, date, time classes.

---

jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/DefaultGenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/FormatRule.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/CustomDatesIT.java
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java

Cleans up some minor issues with the new date time functionality:
1. correct formatting
2. make documentation consistent with existing documentation
3. fail with `GenerationException` if date/time types are specified, but cannot be loaded.

Cleanup for new date time type feature

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/PrefixSuffixIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/properties/primitivePropertiesNoJavaType.json

Please let me know if I need:
* More tests
* More comments
* Style changes
* Alternate behaviour (e.g. capitlization on nodeName and prefix)
Thanks,
Philip

Prefix / Suffix support when javaType is not specified

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/Inflector.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/util/InflectorTest.java

Resolved #479.
Couldn't use the irregular feature as the "men" rule would still produce "speciman" as the singular.

Fixed "specimen" singular.

---

jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/DynamicPropertiesIT.java
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java

Changes the default value of `includeDynamicAccessors` to `false`.

includeDynamicAccessors default false

---

jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
jsonschema2pojo-cli/src/test/java/org/jsonschema2pojo/cli/ArgumentsTest.java

This is a breaking change.
Removes the `--disable-dynamic-accessors`/`-dda` option and replaces it with an `--include-dynamic-accessors`/`-ida` option instead.

Change includeDynamicAccessors default to false in the CLI.

---

jsonschema2pojo-cli/src/test/java/org/jsonschema2pojo/cli/ArgumentsTest.java

ArgumentsTest test use an absolute *ux stype path. On Windows the Java FileSystem implementation converts it to a valid Windows path, that is, a C: is prepended to it. If instead a relative path is used by the test, the returned URL will contain the path to the project as well. This way in both cases we have to check whether the returned URL ends with the expected path, which is done by this commit. It fixes the #484 issue.
Actually the reason for the issue is absolutely the same as for the issue #485.

Issue 484 fix

---

jsonschema2pojo-cli/src/test/java/org/jsonschema2pojo/cli/UrlConverterTest.java

`UrlConverterTest.urlIsCreatedFromFilePath` uses an absolute *ux stype path. On Windows the Java FileSystem implementation converts it to a valid Windows path, that is, a `C:` is prepended to it. If instead a relative path is used by the test, the returned URL will contain the path to the project as well. This way in both cases we have to check whether the returned URL ends with the expected path, which is done by this commit. It fixes the #485 issue

Issue 485 fix

---

jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/util/Jsonschema2PojoRule.java

Path separator is now properly escaped in the regular expression used in Jsonschema2PojoRule. This solves the #486 issue.

Fix for issue 486

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/JavaNameRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/PropertyRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/RuleFactory.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/JavaNameIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/javaName/duplicateDefaultName.json
jsonschema2pojo-integration-tests/src/test/resources/schema/javaName/duplicateName.json
jsonschema2pojo-integration-tests/src/test/resources/schema/javaName/javaName.json

This PR adds an option for defining custom field names instead of the ones inferred from property names. For example, this:
```json
{
"type": "object",
"a": {
"javaName": "b",
"type": "string"
}
}
}
```
will generate this:
```java
@JsonInclude(JsonInclude.Include.NON_NULL)
@Generated("org.jsonschema2pojo")
@JsonPropertyOrder({
"a"
})
public class SimpleTest {
/**
* 
* Corresponds to the "a" property.
* 
*/
@JsonProperty("a")
private String b;
/**
* 
* Corresponds to the "a" property.
* 
* @return
*     The b
*/
@JsonProperty("a")
public String getB() {
return b;
}
/**
* 
* Corresponds to the "a" property.
* 
* @param b
*     The b
*/
@JsonProperty("a")
public void setB(String b) {
this.b = b;
}
/* ... */
}
```

Add javaName schema property

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/DynamicPropertiesRule.java
jsonschema2pojo-integration-tests/pom.xml
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/CompilerWarningIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/util/CodeGenerationHelper.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/util/Compiler.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/util/Jsonschema2PojoRule.java
pom.xml

This PR adds an integration test to detect compilation warnings in the source files generated by the project.  Warnings being produced by the includeDynamicAccessors feature have also been resolved.
__Note__: there is currently a bug with the Eclipse compiler that causes it to report suppressed warnings.  In those cases, the warnings being suppressed have been allowed.
Fixes #498

Remove unused suppress warning annotations

---

jsonschema2pojo-gradle-plugin/example/android/app/build.gradle
jsonschema2pojo-gradle-plugin/example/android/app/src/main/java/jsonschema2pojo/joelittlejohn/github/com/androidexample/MainActivity.java
jsonschema2pojo-gradle-plugin/example/android/build.gradle
jsonschema2pojo-gradle-plugin/example/android/gradle/wrapper/gradle-wrapper.properties
jsonschema2pojo-gradle-plugin/example/android/lib/build.gradle
jsonschema2pojo-gradle-plugin/example/android/lib/src/main/java/jsonschema2pojo/joelittlejohn/github/com/androidlibexample/AndroidLibExample.java
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/GenerateJsonSchemaAndroidTask.groovy
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/GenerateJsonSchemaJavaTask.groovy
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaPlugin.groovy

Hi,
I'm an Android developer,
I use this project on a daily basis by utilizing the cli during our project's build process.
I tried to use the gradle plugin but unfortunately it didn't compile correctly, although the source code was generated correctly, it seems that the generated code isn't added to the source set of the project correctly.
I'm using several kinds of build variants which are essentially different build setups, when using this advanced configuration, the generated code must be added to each build variant's source set.
Although the gradle plugin's code does something like that, it doesn't actually compile when the project's code depends on the generated code.
I've reproduced compilation errors on the android example code projects in the gradle plugin's source code.
In this …

Android gradle plugin fixes

---

jsonschema2pojo-integration-tests/pom.xml
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/CompilerWarningIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/util/Jsonschema2PojoRule.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/util/Jsonschema2PojoRuleTest.java
pom.xml

Capturing diagnostics in the Jsonschema2pojoRule was removing output from STDERR.  This makes that feature optional and adds a test to make sure STDERR output is generated when there are compilation problems.

Jsonschema2pojoRule report problems to STDERR

---

jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/DefaultGenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/DefaultRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/TypeRule.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/TypeRuleTest.java
jsonschema2pojo-gradle-plugin/README.md
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/json/JsonTypesIT.java
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java

I stumbled upon issue #161 and took the commit mentioned there (c182b93bda6) and re-applied it to master. 
This PR adds a config property that allows mapping of number types to BigDecimal instead of Floats

Adds support for mapping BigDecimal as mentioned in issues #161

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/DynamicPropertiesRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/EnumRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/PropertyRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/RequiredArrayRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/NameHelper.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/EnumRuleTest.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/RequiredArrayRuleTest.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/JavaNameIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/javaName/javaNameWithRequiredProperties.json

The previous implementation of `javaName` rule was causing required properties to not be annotated properly (and probably breaking other things). This PR is intended to fix that by better integrating the feature into the project's structure.
`javaName` is applied now within the `NameHelper` class so that the other modules can take it into account while resolving generated Java fields. This requires passing the `JsonNode` of the relevant property to the helper method alongside the property's name. Some of the other modules have been altered to reflect that.

Fix javaName breaking required properties

---

CONTRIBUTORS.md
jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
jsonschema2pojo-core/pom.xml
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/AnnotationStyle.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Annotator.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/AnnotatorFactory.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Moshi1Annotator.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/AnnotatorFactoryTest.java
jsonschema2pojo-gradle-plugin/README.md
jsonschema2pojo-gradle-plugin/example/android/app/build.gradle
jsonschema2pojo-gradle-plugin/example/android/lib/build.gradle
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/Moshi1IT.java
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java
pom.xml

Add Moshi 1.x annotation style

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/PropertiesRule.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/ExtendsIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/extends/b.json
jsonschema2pojo-integration-tests/src/test/resources/schema/extends/subtypeOfB.json
jsonschema2pojo-integration-tests/src/test/resources/schema/extends/subtypeOfBWithNoProperties.json

Override parent builders even if the child schema has no properties

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/ExtendsIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/extends/c.json
jsonschema2pojo-integration-tests/src/test/resources/schema/extends/subtypeOfC.json
jsonschema2pojo-integration-tests/src/test/resources/schema/extends/subtypeOfSubtypeOfB.json
jsonschema2pojo-integration-tests/src/test/resources/schema/extends/subtypeOfSubtypeOfBDifferentType.json
jsonschema2pojo-integration-tests/src/test/resources/schema/extends/subtypeOfSubtypeOfC.json

So this isn't the prettiest, but it might do for now.
There's at least 2 new recursive methods and I had to make use of 'instanceof' :(
what do you think to storing classes JFieldVar's on the schema object? It would remove the need for the `instanceof` call...?

Fix for extends with constructor

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/IncludeHashCodeAndEqualsIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/hashCodeAndEquals/extendsEmpty.json
jsonschema2pojo-integration-tests/src/test/resources/schema/hashCodeAndEquals/types.json

In these generated methods, call the super version only if
the type does not extend java.lang.Object.
Fix #610.

Generate hashCode and equals even without declared fields

---

jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/DefaultGenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/DefaultRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/TypeRule.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/TypeRuleTest.java
jsonschema2pojo-gradle-plugin/README.md
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/DefaultIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/json/JsonTypesIT.java
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java

Add option to use BigInteger for JSON integer type

---

jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy

This allows me to pass in an annotator implementation defined in the gradle file, which otherwise was throwing ClassNotFoundException.

Allow setting custom annotator and custom rule factory fields directly in Gradle

---

jsonschema2pojo-gradle-plugin/README.md

I've just created a "plain old" gradle project. 
Only for creating the json files to objects. Don't want to import it in my android project. 
So it ended up with:
```java
* What went wrong:
A problem occurred evaluating root project 'pojoGen'.
> Failed to apply plugin [id 'jsonschema2pojo']
> generateJsonSchema: Java or Android plugin required
```
For further readers it would be great to know that info ;)

Add plugin infos

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Jackson2Annotator.java

Fixes #655 so that the description from the schema is now properly set in the @JsonPropertyDescription annotation.

 #655 @JsonPropertyDescription fix

---

jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java

The argument `disable-additional-properties` was passed directly into `isIncludeAdditionalProperties`, which meant that when it was true, additional properties were included, and vice versa.
This changes the argument to `*enable*-additional-properties`, and passes it directly to `isIncludeAdditionaProperties`

Fix include additional properties set incorrectly by CLI

---

jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/AbstractAnnotator.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Annotator.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/CompositeAnnotator.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/DefaultGenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Jackson2Annotator.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/PropertyRule.java
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/CustomDateTimeFormatIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/CustomAnnotatorIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/format/customDateTimeFormat.json
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java

Adds @JsonFormat annotation to specified property. An example of the jsonschema is:
```
{
"type" : "object",
"properties" : {
"stringAsJavaDate" : {
"type" : "string",
"format" : "date-time",
"customDateTimePattern" : "yyyy-MM-dd'T'HH:mm:ss.SSSZ",
"timezone" : "PST"
},
"stringAsJodaDateTime" : {
"javaType" : "org.joda.time.DateTime",
"format" : "date-time",
"customDateTimePattern" : "yyyy-MM-dd'T'HH:mm:ss.SSSZ",
"timezone" : "PST"
}
}
}
```
This PR is not ready to be merged. I created this to get feedback. I am still trying to get the integration tests to work.

Support for @JsonFormat annotation

---

jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/DefaultGenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/FragmentResolver.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/SchemaStore.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/PropertyRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/SchemaRule.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/FragmentResolverTest.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/SchemaStoreTest.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/SchemaRuleTest.java
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/CustomSeparatorCharactersIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/RefFragmentPathDelimitersIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/properties/nonStandardRef.json
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java

This adds the option suggested in #688, so nonstandard JSON Pointers found in $ref can be split correctly.
The option's default is the current value, `#/.`, so it should not break any existing projects.
Let me know if something is missing and needs to be done before merging, also let me know if the wording of the descriptions is a bit weird.

Add option to specify custom separator characters

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/PrefixSuffixIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/properties/objectPropertiesJavaType.json

Fixes #650 
For the test I needed to use a package other than java.util, or a security exception is thrown.

Don't prefix a class if it already exists without the prefix.

---

.travis.yml

Let Travis check Clojure syntax.
Travis ignores the gh-pages branch by default, we have to explicitly include it:
https://docs.travis-ci.com/user/customizing-the-build#Safelisting-or-blocklisting-branches

Enable Travis CI for gh-pages

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/DefaultRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/EnumRule.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/EnumRuleTest.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/DefaultIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/EnumIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/default/default.json

Use the correct argument type for the factory method and the constructor of enums with non-string backing types: number and integer.

Fix compilation errors for non-string enums

---

jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/DefaultGenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/IncludeToStringExcludesIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/IncludeToStringIT.java
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java

We need the ability to exclude certain fields ( for example passwords ) from the generated toString methods, as these toString methods are invoked by some logging statements.
This PR adds support for excluding fields by name from the toString method , using the builtin support for this feature in the CommonsLang(3) ReflectionToStringBuilder:
https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/builder/ReflectionToStringBuilder.html#toStringExclude-java.lang.Object-java.lang.String...-
A new optional string array parameter `toStringExcludes` is added to support this

Add support for excluding fields from generated toString methods

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/RequiredArrayRule.java
jsonschema2pojo-integration-tests/src/test/resources/schema/required/requiredArray.json

In my project I've hit the #725 issue - while working with `machine generated` schema, that contains an empty element in `required` array.
For verification purposes I've used slightly modified schema from #725 (added nonempty element to mix up empty and nonempty ones in array).
```
{
"$schema": "http://json-schema.org/draft-04/schema#",
"title": "Silly",
"type":"object",
"description":"silly example",
"required": ["", "code", ""],
"code" : {
"type":"string",
"description":"blah blah blah"
}
}
}
```
Also the schema was changed `requiredArray.json` (added empty element to `required` array) to make integration test fail when run without the change.

Fix for 725

---

jsonschema2pojo-gradle-plugin/README.md

The version suggested in the Gradle Plugin README is a version of jackson that doesn't have the `com.fasterxml.jackson.annotation.JsonPropertyDescription` annotation.
The new recommended version has the annotation.

Update recommended jackson version gradle plugin

---

jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/AbstractAnnotator.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Annotator.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/CompositeAnnotator.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/DefaultGenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Jackson2Annotator.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/FormatRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/PropertyRule.java
jsonschema2pojo-gradle-plugin/README.md
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/CustomDateTimeFormatIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/CustomAnnotatorIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/format/customDateTimeFormat.json
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java

The default format is HH:mm:ss.SSS and can be overridden by
specifying a customTimePattern property.

Added support for formatting times

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/ParcelableHelper.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/ParcelableIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/util/ParcelUtils.java
jsonschema2pojo-integration-tests/src/test/resources/schema/parcelable/parcelable-superclass-data.json
jsonschema2pojo-integration-tests/src/test/resources/schema/parcelable/parcelable-superclass-schema-base.json
jsonschema2pojo-integration-tests/src/test/resources/schema/parcelable/parcelable-superclass-schema.json

When a generated `Parcelable` model subclasses another `Parcelable` model, the subclass needs to call its parent to allow the parent's properties to be written to/read from the `Parcel`
- Calls `super.writeToParcel` if the parent implements `Parcelable`
- Creates a protected constructor with a Parcel as a single parameter that reads from the `Parcel`, calling `super(in)` if the parent implements `Parcelable`
- Moved the read from `Parcel` code that used to be into `CREATOR#createFromParcel` to the newly created constructor; `createFromParcel` now just returns `new Ctor(in)` instead.
- Explicitely added an empty constructor since the newly added ctor shadows the default empty one

Fix for #602 : Writing to /Reading from Parcelable ignores superclass

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/ParcelableIT.java

Fix regression introduced by #602 when configuration option `includeConstructors` is true : empty default constructor added twice.
Updated existing integration test and added another one; test Parcelable generation with the option on and off to ensure compilation and serialization/deserialization work properly.
Please let me know if there other configurations that may generate an empty constructor (I looked through the code and couldn't find any).

Fix for #742 : Generating 2 constructors

---

jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/GenerateJsonSchemaJavaTask.groovy

Fixes issue #744 where up-to-date check depends on inputs and outputs collection detecting changes automatically in configured source/target files
testcase:
cd /jsonschema2pojo-gradle-plugin/example/java
./gradlew build (:generatedJsonSchema2Pojo UP-TO-DATE)
change address.json
./gradlew build (:generatedJsonSchema2Pojo will be executed)
./gradlew build (:generatedJsonSchema2Pojo UP-TO-DATE)

Gradle plugin up to date check

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java

For the same reasons as #150 changed `hashCode()` and `equals()`, generate `toString()` methods that do not use reflection to find the fields of the POJO.

Generate toString() without reflection

---

jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
jsonschema2pojo-cli/src/test/java/org/jsonschema2pojo/cli/ArgumentsTest.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/DefaultGenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/DynamicPropertiesRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/PropertyRule.java
jsonschema2pojo-gradle-plugin/README.md
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/AdditionalPropertiesIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/CompilerWarningIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/DynamicPropertiesIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/IncludeAccessorsIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/IncludeAccessorsPropertiesIT.java
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java

Made it possible for getters and setters to be activated independently. I am not sure that I did the dynamic setters/getters correctly, so any feedback will be appreciated. I would also like feedback on the testing.

Getters and Setters can now be activated independently

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/ExcludedFromEqualsAndHashCodeIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/excludedFromEqualsAndHashCode/excludedFromEqualsAndHashCode.json

Added `excludedFromEqualsAndHashCode` option for specifying which properties should be excluded from `equals()` and `hashCode()` methods. It can be used both as an object-level array containing excluded property names or as a property-level boolean switch.
Example:
```
{
"type": "object",
"excludedFromEqualsAndHashCode" : [ "excludedByArray" ],
"notExcluded" : {
"type" : "string"
},
"excludedByProperty" : {
"type" : "string",
"excludedFromEqualsAndHashCode" : true
},
"notExcludedByProperty" : {
"type" : "string",
"excludedFromEqualsAndHashCode" : false
},
"excludedByArray" : {
"type" : "string"
}
}
}
```
`notExcluded` and `notExcludedByProperty` will be used while generating `hashCode()` and `equals()`, while `excludedByProperty` and `excludedByArray` won't.
I felt that …

#309 - Make the fields used in hashcode and equals generation configurable

---

jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java

Use FilenameUtils to fix relative source paths in the maven plugin.  This in turn fixes the extra "underscore" classes that get generated with a relative source path.

Use FilenameUtils to fix relative source paths (and remove extra underscore classes that appear when using a relative source path)

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/TypeUtil.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/util/TypeUtilTest.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/GenericTypeIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/type/genericJavaType.json

Added support for the following syntax in "javaType" declarations:
- `?`
- `? extends ...`
Unfortunately, due to limitations of [Sun JCodeModel](https://github.com/javaee/jaxb-codemodel/blob/master/codemodel/codemodel/src/main/java/com/sun/codemodel/JTypeWildcard.java) it is impossible to add support for `? super ...`
Maybe it is time to think about using a more comprehensive and better maintained [JCodeModel fork](https://github.com/phax/jcodemodel/)?

add partial support of wildcards in "javaType" declarations

---

jsonschema2pojo-scalagen/pom.xml
pom.xml

Looks like there are dependency version inconsistencies in the latest POM:
```
Dependency convergence error for org.apache.commons:commons-lang3:3.0.1 paths to dependency are:
+-org.jsonschema2pojo:jsonschema2pojo-core:0.5.1
+-org.jsonschema2pojo:jsonschema2pojo-scalagen:0.5.1
+-org.apache.commons:commons-lang3:3.0.1
and
+-org.jsonschema2pojo:jsonschema2pojo-core:0.5.1
+-org.apache.commons:commons-lang3:3.2.1
```
It appears that the scalagen module uses a different version of commons-lang3 than the core module.
The below commits should address this and also a few minor tweaks to the POM to better use managed dependencies from the root POM.

Inconsistencies in Maven POMs

---

jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/CustomDateTimeFormatIT.java
jsonschema2pojo-scalagen/src/test/scala/com/mysema/examples/SuperConstructors.java
jsonschema2pojo-scalagen/src/test/scala/com/mysema/scalagen/SerializationTest.scala

There were two tests failing:
* one in SerializationTest, because OSX's case insensitive file system found a different Superclass definition than the SuperClass it was meant to find
* one in CustomDateTimeFormatIT because the JSON serializer was using the system locale and the test was expecting results with english locale.

Fix failing tests

---

jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Jsonschema2PojoCLI.java
jsonschema2pojo-core/pom.xml
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/DefaultGenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java
jsonschema2pojo-gradle-plugin/README.md
jsonschema2pojo-gradle-plugin/example/android/app/build.gradle
jsonschema2pojo-gradle-plugin/example/android/lib/build.gradle
jsonschema2pojo-gradle-plugin/example/java/build.gradle
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/GenerateJsonSchemaAndroidTask.groovy
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/GenerateJsonSchemaJavaTask.groovy
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/ToStringIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/CommonsLangRemovalIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/IncludeToStringExcludesIT.java
jsonschema2pojo-integration-tests/src/test/resources/ant/build.xml
jsonschema2pojo-integration-tests/src/test/resources/schema/toString/arrayOfArrays.json
jsonschema2pojo-integration-tests/src/test/resources/schema/toString/compositeTypes.json
jsonschema2pojo-integration-tests/src/test/resources/schema/toString/intPair.json
jsonschema2pojo-integration-tests/src/test/resources/schema/toString/polygon.json
jsonschema2pojo-integration-tests/src/test/resources/schema/toString/quadrilateral.json
jsonschema2pojo-integration-tests/src/test/resources/schema/toString/scalarTypes.json
jsonschema2pojo-integration-tests/src/test/resources/schema/toString/square.json
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java
jsonschema2pojo-maven-plugin/src/test/resources/example/pom.xml
jsonschema2pojo-maven-plugin/src/test/resources/filtered/pom.xml
pom.xml

commons-lang is a *relatively* large library for users to include just for adding `toString()`, `equals()`, and `hashCode()`. This removes that dependency and uses generated code instead.
It avoids calls like `Objects.hash()`, `Double.hashCode()`, and `Objects.equals()` that were added in later versions of Java.
Generated code looks something like this:
```
public class ComplexTypesArray {
@Override
public String toString() {
StringBuilder sb = new StringBuilder();
sb.append(ComplexTypesArray.class.getName())
.append('@')
.append(Integer.toHexString(System.identityHashCode(this)))
.append('[');
sb.append("additionalProperties");
sb.append('=');
sb.append(((this.additionalProperties == null)?"<null>":this.additionalProperties));
sb.append(',');
if (sb.charAt((sb.length()- 1)) == ',') { …
```

Replace commons-lang equals, hashCode, and toString with generated code

---

jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/DefaultGenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/PropertyRule.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/example/Example.java
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java

This is just a draft - I would like to get some comments from you on the initial direction. Would it work this way or am I on the wrong track?
And is there a good reason why there are no tests for PropertyRule? (If not I'd implement a few happy path tests).
Fixes #342

add useJava8OptionalForNonRequiredFields option

---

pom.xml

As far as I understand the need for the explicit repository, this could be a solution in strict nexus/artifactory environments.

#832 Changed maven central repo listing id key to default

---

jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/DefaultGenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/FormatRule.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/FormatRuleJodaTest.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/FormatRulePrimitivesTest.java
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/FormatTypeMappingIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/format/nonStandard.json
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java

This commit introduces a new option `formatTypeMapping`, which maps from format
(e.g. 'uri') to type (e.g. 'java.net.URI'). The current base types and configurations
are left as-is. This means, that it is still possible to set 'useJodaDate' or 'dateType'
as before. Alternatively, a mapping 'date' > 'org.joda.time.LocalDate' achieves the same
output.
With this change it is also possible to map non-standard formats to types. This logic is
intentional, but not recommended to users as it invalidates the schema.
This (partly) fixes gh-910 and is an alternative to gh-918.

Add 'formatTypeMapping' config option to allow overriding types used for formats

---

jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/GenerateJsonSchemaJavaTask.groovy

In order for task caching to work, tasks have to define their inputs and
outputs. These are defined as a set of files, directories, properties
and such.
Until Gradle 4.3 defining inputs was very lax - you could pass
directories in place of files and vice versa. Starting with 4.3
there is a set of validators which check for this and issue
a warning if at configuration time the declared type of file
(directory/normal file) doesn't match the filesystem.
Starting with 5.0, these warnings are now errors - while the task works
just fine on the first build, subsequent ones discover that the output
is a directory, while it's defined in two places as both a file and a
directory - this fails the build at configuration time (even if the task
is not ran).
Removal of this line resolves #809 by …

Don't register output directory as a set of files, since this breaks Gradle 5.0+

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/PropertyRule.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/PropertyRuleTest.java

Hi,
The generated code is incorrect when a required field is an object, and it has required internal fields. It because of wrong algorithm checks is required flag of the field previously than tests a top defined required fields list. I've changed the checking order.
I mean the case where is the top schema follows:
```json
{
"$schema": "http://json-schema.org/draft-07/schema#",
"type": ["object", "null"],
"required": [
"payment_type",
"change_alignment",
"billing_alignment"
],
"payment_type": {
"type": "object",
"$ref": "payment_type.json"
},
"change_alignment": {
"type": "object",
"$ref": "change_alignment.json"
},
"billing_alignment": {
"type": "object",
"$ref": "billing_alignment.json"
}
}
}
```
and `billing_alignment.json` is:
```json
{
"$schema": …
```

Check schema required array before is required flag

---

jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/AbstractAnnotator.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/AbstractTypeInfoAwareAnnotator.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Annotator.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/CompositeAnnotator.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/DefaultGenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Jackson1Annotator.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Jackson2Annotator.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/PolymorphicIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/CustomAnnotatorIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/IncludeJsonTypeInfoAnnotationIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/IncludeTypeInfoIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/typeInfo/typeInfo.json
jsonschema2pojo-integration-tests/src/test/resources/schema/typeInfo/typeInfoWithSchemaProperty.json
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java

Add support for including the Jackson 1 & 2 JsonTypeInfo Annotation to generated classes.

Add support for including JsonTypeInfo Annotation

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/EnumRule.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/DescriptionEnumIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/TitleEnumIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/description/descriptionEnum.json
jsonschema2pojo-integration-tests/src/test/resources/schema/title/titleEnum.json

Add support for titles and descriptions within Javadocs for root-level enums.

#975 add enum documentation

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/DigitsRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/PropertyRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/RuleFactory.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/RuleFactoryImplTest.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/IncludeJsr303AnnotationsIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/jsr303/digits.json

Fix to #977.
Implementation notes:
Requires use of a `digits` field that is associated with a property, which in turn requires `integerDigits` and `fractionalDigits` to be set within that `digits` field.
For example (this assumes that the config option of `isUseBigDecimals()` returns true).
```
{
"type" : "object",
"properties" : {
"decimal" : {
"type" : "number",
"digits" : {
"integerDigits": 5,
"fractionalDigits": 10
}
}
}
}
```
Validation of `integerDigits` and `fractionalDigits` is currently restricted to only checking that they exist.  In the event that either does not, DigitsRule will throw an `NoSuchElementException`.

977 add digits rule

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java
jsonschema2pojo-core/src/test/resources/AuthorizeRequest_v1p0.json
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/JavaNameIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/javaName/AuthorizeRequest_v1p0.json
jsonschema2pojo-integration-tests/src/test/resources/schema/javaName/AuthorizeRequest_v1p0_2.json

I am working in a POC with OCPP 1.6/2.0 that use json schemas with a not fully qualified javatype (example attacched). May be useful check if a specified javatype is fqn or not and hence add the package name if needed.

Add package when javaType is not a fully qualified name

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/Inflector.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/util/InflectorTest.java

Previously, another rule incorrectly caused slaves to be singularized as
"slafe"

Fix singularization for "slaves"

---

jsonschema2pojo-cli/pom.xml
jsonschema2pojo-core/pom.xml
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/AbstractRuleLogger.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/DigitsRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/MinItemsMaxItemsRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/MinLengthMaxLengthRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/MinimumMaximumRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/PatternRule.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/DigitsRuleTest.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/MinItemsMaxItemsRuleTest.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/MinLengthMaxLengthRuleTest.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/MinimumMaximumRuleTest.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/PatternRuleTest.java
jsonschema2pojo-core/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
jsonschema2pojo-integration-tests/pom.xml
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/IncludeJsr303AnnotationsIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/jsr303/digits.json
jsonschema2pojo-integration-tests/src/test/resources/schema/jsr303/maxItems.json
jsonschema2pojo-integration-tests/src/test/resources/schema/jsr303/maxLength.json
jsonschema2pojo-integration-tests/src/test/resources/schema/jsr303/maximum.json
jsonschema2pojo-integration-tests/src/test/resources/schema/jsr303/minItems.json
jsonschema2pojo-integration-tests/src/test/resources/schema/jsr303/minLength.json
jsonschema2pojo-integration-tests/src/test/resources/schema/jsr303/minimum.json
jsonschema2pojo-integration-tests/src/test/resources/schema/jsr303/pattern.json
jsonschema2pojo-integration-tests/src/test/resources/schema/jsr303/validAdditionalProperties.json
pom.xml

I found that JSR-303 annotations were getting applied to types that didn't support them. For example, if a "pattern" was specified on a "string" property that also had a "format" of "uuid", then the generated field type is `UUID` class (rather than `String`) and `@Pattern` was still applied. Because that annotation isn't valid on a `UUID` type, then validators generate errors.
Continuing with this example, because a schema may be used to generate source classes in non-Java languages, there is still value to keep the "pattern" restriction on the source json schema itself for languages that might not have an in-built UUID type. 
This patch updates the various JSR-303 Rules classes to enhance them to check the generated class type of potentially annotated fields against the classes/types …

Restrict JSR-303 annotations to supported field types

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/model/EnumDefinition.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/model/EnumDefinitionExtensionType.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/model/EnumValueDefinition.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/DefaultRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/DescriptionRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/EnumRule.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/TitleRuleTest.java
jsonschema2pojo-gradle-plugin/src/test/groovy/org/jsonschema2pojo/gradle/JsonSchemaPluginSpec.groovy
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/EnumIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/enum/enumWithJavaEnumsExtension.json

Implement javaEnums extension to extend on what javaEnumNames provided.

Implement javaEnums extension 

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/SchemaStore.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/SchemaStoreTest.java
jsonschema2pojo-core/src/test/resources/schema/person.json

Added a unit test to show how URIs with relative path segments will cause a recursive schema model to generate two classes with a difference in name only. Also added a fix for the code as well
#1075

Recursive schemas with relative paths can generate the same class twice with "__1" in the name

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/SchemaStore.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/SchemaStoreTest.java

I apologize, but I missed a test case that exposed that fact that the fix was not complete. I wanted the SchemaStore to return the same object instance and it was not. I updated it to do so now and added the test to validate it.
#1077

Missing test case

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/AdditionalPropertiesRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/BuilderRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ConstructorRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/PropertyRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/NameHelper.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/ReflectionHelper.java

Existing inner class builders did not define a type so they could be inherited but whenever you use the builder you would get a IDE/code scanner warning about using a raw type.
This makes the existing builder abstract and adds Base to the end.  All classes extending this class would inherit from this "Base" builder.
A concrete builder is created which extends the "Base" builder and resolves the generic type.

Fix raw type warnings when extending a builder

---

jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/ExcludedFromEqualsAndHashCodeIT.java
license-plugin-definition.xml
pom.xml

This problem happens on windows and usually I have to revert the corrupted character out of copyright notice before committing.

Update license plugin to fix corrupted character before copyright symbol

---

jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java

The fields `includeRequiredPropertiesConstructor`, `includeAllPropertiesConstructor`, and `includeCopyConstructor` in the maven plugin cannot be configured in the pom. They are ignored by maven because they are missing the private modifier. This pull request adds this modifier.

added private modifier to configuration options where missing

---

jsonschema2pojo-gradle-plugin/README.md

As discussed in issue https://github.com/joelittlejohn/jsonschema2pojo/issues/1070 this MR:
-  marks gradle plugin in current repo as deprecated 
- and adds link to the actively maintained plugin from the separate repo.

Deprecate gradle plugin and add the link to the new actively maintained gradle plugin

---

jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/DefaultGenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/EnumRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/AnnotationHelper.java
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/IncludeGeneratedAnnotationIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/includeGeneratedAnnotation/includeGeneratedAnnotation.json
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java

Restores the feature which added @javax.annotation.Generated annotation to generated code. In addition, the feature becomes conditional on a boolean configuration property "markGenerated" (as in JAXB. openapi ecc...), defaulted to false.
Addresses #1162 and related, without falling back to #577.

Add @Generated annotation to classes and includeGeneratedAnnotation config option

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/SchemaStore.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/AdditionalPropertiesRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ArrayRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/PropertyRule.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/ArrayRuleTest.java

~~This is a very large PR as it includes changes from #560 and #558. The diff should therefore decrease if those changes are accepted~~
This is a change to the way the schemastore is used, essentially it's used more, for every potential object schema we come across.
There is also the beginnings of a context-like object in ObjectRule, call `SchemaClassInfo`. It may look a bit confusing having both the `classHierarchySchema` and `classDefinitionSchema` in as separate instance, but this allows a layer of indirection between the two which allows me to support `allOf` in a very simple way (only where it is exactly equivalent to extends) - see this https://github.com/samskiter/jsonschema2pojo/commit/94d9f1083a23df245b93de493717c9c053026a5d
I appreciated that you might not want to add allOf …

Schema contract changes

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/Inflector.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/util/InflectorTest.java

Split and modify `"([ti])a$"` Inflector rule as outlined in https://github.com/joelittlejohn/jsonschema2pojo/issues/1275#issuecomment-866767985

Split and modify "([ti])a$" Inflector rule

---

jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
jsonschema2pojo-core/pom.xml
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/DefaultGenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/DigitsRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/MinItemsMaxItemsRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/MinLengthMaxLengthRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/MinimumMaximumRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/PatternRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/RequiredArrayRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/RequiredRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ValidRule.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/DigitsRuleTest.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/MinItemsMaxItemsRuleTest.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/MinLengthMaxLengthRuleTest.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/MinimumMaximumRuleTest.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/PatternRuleTest.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/RequiredArrayRuleTest.java
jsonschema2pojo-gradle-plugin/README.md
jsonschema2pojo-gradle-plugin/example/android/app/build.gradle
jsonschema2pojo-gradle-plugin/example/android/lib/build.gradle
jsonschema2pojo-gradle-plugin/example/java/build.gradle
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy
jsonschema2pojo-integration-tests/pom.xml
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/IncludeJsr303AnnotationsIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/IncludeJsr305AnnotationsIT.java
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java
pom.xml

- As suggested in https://github.com/joelittlejohn/jsonschema2pojo/issues/1271#issuecomment-871246569 - added `useJakartaValidation` (default `false`) as a new configuration option
- Using `apache bval` for `javax.validation` and `hibernate-validator` for `jakarta.validation` in integration tests
- Unit tests are done using `@Parameterized` to check both cases (`javax.validation` and `jakarta.validation`) alternatives could be
- duplicate test methods with addition of `useJakartaValidation` configuration option
- duplicate test classes with addition of `useJakartaValidation` configuration option

Support usage of JSR-303 annotations from 'jakarta.validation' package

---

jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/SchemaMapperTest.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/SourceSortOrderTest.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/DigitsRuleTest.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/EnumRuleTest.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/MinItemsMaxItemsRuleTest.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/MinLengthMaxLengthRuleTest.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/MinimumMaximumRuleTest.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/PatternRuleTest.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/SchemaRuleTest.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/TypeRuleTest.java

Replaced deprecated mockito methods that were removed in `4.0.0` (https://github.com/joelittlejohn/jsonschema2pojo/pull/1345)
Additionally:
- removed unused import statements
- removed redundant casts
- removed redundant `throws IOException`
- added `final` modifier to fields

Replaced deprecated mockito method calls, minor other improvements

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/AdditionalPropertiesRule.java

Original GitHub issue:
> It's quite annoying that additionalProperties values lose their initial array order when json is parsed.
> Since I use the same schema classes to generate json after tweaking, I can't sort them too.
> I guess it will be easy to add an option to generate LinkedHashMap instead of HashMap for additionalProperties field.

Use LinkedHashMap for additional properties, so the original ordering in the JSON is preserved

---

jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
jsonschema2pojo-core/pom.xml
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/AnnotationStyle.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/AnnotatorFactory.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Jsonb1Annotator.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Jsonb2Annotator.java
jsonschema2pojo-gradle-plugin/README.md
jsonschema2pojo-integration-tests/pom.xml
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/GsonIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/Jsonb1IT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/Jsonb2IT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/JsonbIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/Moshi1IT.java
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java

My suggestion for JSON-B-support. I have provided two annotators for JSON-B 1 and 2. They differ only in the package of the annotations though. Alternatively, one could provide a baseclass, too, and let the two extending classes only provide the annotation classes. Thiw, however, would lead to a close coupleing of both versions. Another alternative would be to have the subversion be specified by the configuration of the plugin and provide one class that handles both versions by respecting the configuration. Thought I leave that decision up to you.

Added support for JSON-B

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/BuilderRule.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/UseInnerClassBuildersIT.java

This PR updates the code to add a `public static` method called `builder` to all the classes that are created with the `generateBuilders` and `useInnerClassBuilders`.
This is a sample of how the builder method looks like:
```
public static Child.ChildBuilderBase builder() {
return new Child.ChildBuilder();
}
```
Fixes #1396

Adds builder method when using innerBuilder

---

jsonschema2pojo-gradle-plugin/README.md

The default for both values is `true`, according to
https://github.com/joelittlejohn/jsonschema2pojo/blob/2d55620ac925ff7406f2982a2c37d49a6697cd20/jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy#L146-L147

correct gradle default values for includeGetters/includeSetters

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/FragmentResolver.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/JsonPointerUtils.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/PropertyRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/ReflectionHelper.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/JsonPointerUtilsTest.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/PropertiesIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/properties/propertiesWithSpecialCharacters.json

When creating a fragment with JSON Pointer path, we now encode property names using the rules from RFC 6901. This means that the property name can be treated as a single token, even if it contains special characters like # or /.
Closes #1402

Encode property names when building path to property

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/PropertyRule.java
jsonschema2pojo-integration-tests/pom.xml
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/IncludeJsr303AnnotationsIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/jsr303/email.json
pom.xml

Things to consider if are using the includeJsr303Annotations feature:
* If you have useJakartaValidation turned on, you'll now see `jakarta.validation.constraints.Email` added to a property when using `"format":"email"`.
* If don't have useJakartaValidation turned on, you'll now see [`javax.validation.constraints.Email`](https://javaee.github.io/javaee-spec/javadocs/javax/validation/constraints/Email.html) added to a property when using `"format":"email"`.
* The Email annotation is introduced in the bean validation spec 2.0, so you will need to upgrade to javax.validation:validation-api 2.x (2.0.1.Final is a good choice). Note, all old annoations are maintained (with the same fully-qualified name) so upgrading this should not break anything.
* If email validation is still not happening, …

Add Email bean validation annotation for "format":"email"

---

jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ArrayRule.java
jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/EnumRule.java
jsonschema2pojo-integration-tests/pom.xml
jsonschema2pojo-maven-plugin/pom.xml
jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java
pom.xml

Switch from Javadoc tags to Mojo Annotations to reduce amount of warnings emitted during build:
```
Warning:  /home/runner/work/jsonschema2pojo/jsonschema2pojo/jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java:65: warning - @goal is an unknown tag.
Warning:  /home/runner/work/jsonschema2pojo/jsonschema2pojo/jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java:65: warning - @phase is an unknown tag.
Warning:  /home/runner/work/jsonschema2pojo/jsonschema2pojo/jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java:65: warning - @requiresDependencyResolution is an unknown tag.
Warning:  /home/runner/work/jsonschema2pojo/jsonschema2pojo/jsonschema2pojo-maven-plugin/src/mai …
```

Use Mojo Annotations instead of Javadoc tags

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ConstructorRule.java
jsonschema2pojo-integration-tests/pom.xml
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/ConstructorsIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/ConstructorsJavadocIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/DescriptionEnumIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/DescriptionIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/DollarCommentIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/JavaNameIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/RequiredArrayIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/RequiredIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/TitleEnumIT.java
jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/TitleIT.java
jsonschema2pojo-integration-tests/src/test/resources/schema/constructors/javadoc/javadocConstructor.json
pom.xml

Add Javadoc to constructors parameters which have corresponding documented properties.
Properties that are not documented (do not have `title` or `description`) won't be added to constructors Javadoc.
Following format will be used:
```java
/**
* {@param {title. }?{description.}?}?
*/
```
Closes #1463

Add Javadoc to constructors parameters for properties that have title/description/$comment

---

.github/workflows/android-ci.yml
jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/GenerateJsonSchemaAndroidTask.groovy

This fixes the broken targetVersion detection for Gradle Android builds, and also updates the Android Sample GitHub action so that it actually runs against the HEAD code (rather than the latest release).

Fix detection of targetVersion for Android gradle builds

---

jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/AdditionalPropertiesRule.java
jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/AdditionalPropertiesRuleTest.java

A schema's `id` is not guaranteed to be non-null. E.g.
https://github.com/joelittlejohn/jsonschema2pojo/blob/80d827db93e4cc3848c4f297ebbfe4b3fd936272/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/SchemaMapper.java#L89-L91

Avoid NPE when setting additionalProperties path
