- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Jsonschema2Pojo.java
- jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/RegressionIT.java
- jsonschema2pojo-integration-tests/src/test/resources/schema/regression/foo.baz.json
- Fixed issue with files named with the pattern some.ridiculous.extension.prefix.json
- Added integration test to check this
> Patching node name resolution

- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/DefaultRule.java
- jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/DefaultIT.java
- jsonschema2pojo-integration-tests/src/test/resources/schema/default/default.json
This is fix for: https://github.com/joelittlejohn/jsonschema2pojo/issues/320
> Issue #320 Added support for empty default string

- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java
- jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/ExtendsIT.java
- jsonschema2pojo-integration-tests/src/test/resources/schema/extends/subtypeOfA.json
- jsonschema2pojo-integration-tests/src/test/resources/schema/extends/subtypeOfSubtypeOfA.json
This is to address this issue: https://github.com/joelittlejohn/jsonschema2pojo/issues/331
> Add super() to the equals/hashcode impl

- jsonschema2pojo-cli/src/main/scripts/jsonschema2pojo.sh
> Find jar when jsonschema2pojo sh script is not running in script folder

- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/SchemaStore.java
There is no easy way to override schema source expect copying all the logic into a custom schema source and making appropriate changes. Making protected makes my life easy in terms of custom resolution.
> Made members protected to provide a way to write a custom schema source

- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/EnumRule.java
There is no point in the lookup *not* being final really :)
> Make the quick lookup map 'final'

- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/Inflector.java
- jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/util/InflectorTest.java
- Hence got rid of the now superfluous synchronisation & threading test.
- cache Pattern on construction of RuleAndReplacement
(realised the synchronisation I added previously was pointless, which irritated me enough for this patch :))
> Made Inflector clearly immutable by introducing a builder.

- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/PropertiesRule.java
- jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/ExtendsIT.java
@joelittlejohn Could you please review it.
> #455 Override builder methods from parent class

- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/AnnotationStyle.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/DefaultRule.java
- jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/DefaultIT.java
> Use correct default value type for BigDecimal fields

- jsonschema2pojo-gradle-plugin/README.md
Took me a little while to work this out, knowing this would have certainly shortened my debugging loop.
> Added some instructions to help contributors

- jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
- jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
- jsonschema2pojo-gradle-plugin/README.md
I noticed some stuff was missing. Could probably have pushed this directly but it's quite a few changes
> Added missing methods and documentation for prefix/suffix stuff

- jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
- jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
- jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/DefaultGenerationConfig.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/SerializableHelper.java
- jsonschema2pojo-gradle-plugin/README.md
- jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy
- jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/SerializableIT.java
- jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java
Squashed commits:
Tweaks following PR. inline method, change exception and add message (+24 squashed commits)
[d9ef5ae] Move serialisable support out to a utility class.
[30e6eae] Fix null pointer exception when reading constructors, add test for it.
[e5b1fac] Fix missing declared exceptions
[eafc434] Fix types and iterators
[58c23a3] More imports and correct types
[602bf66] more imports, fix iterable
[f143a87] fix imports and indents
[b076cbc] correct method name
[cf87113] don't use keyword as variable name
[0223643] remove diamond operators
[eeefbc8] Fix up syntax errors and since version
[3b09b3b] First cut of serialversionUID support
[67fcb37] add missing semicolon
[875f59f] Added serializable integration test
[a077b01] updated since in maven docs
[3d7977d] added serializable to ant …
> Added serializable support (squashed and rebased)

- jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
- jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
- jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/DefaultGenerationConfig.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Jsonschema2Pojo.java
- jsonschema2pojo-gradle-plugin/README.md
- jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy
- jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/FileExtensionsIT.java
- jsonschema2pojo-integration-tests/src/test/resources/schema/fileExtensions/nameWithExtension.schema.json
- jsonschema2pojo-integration-tests/src/test/resources/schema/fileExtensions/nameWithNoExtension
- jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java
This adds the ability to ignore certain file extensions.
It's something I need personally, but I thought I would show you it and see what you think to including it upstream...?
> Added file extensions config parameter

- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/SchemaStore.java
- jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/SchemaStoreTest.java
- jsonschema2pojo-core/src/test/resources/schema/embeddedRef.json
- jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/ref/SelfRefIT.java
- jsonschema2pojo-integration-tests/src/test/resources/schema/ref/selfRefs.json
I've changed the way schema refs are resolved through schemastore to fix this.
> Fix broken embedded refs

- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/NameHelper.java
- jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/PropertiesIT.java
- jsonschema2pojo-integration-tests/src/test/resources/schema/properties/propertiesAreUpperCamelCase.json
- jsonschema2pojo-integration-tests/src/test/resources/schema/ref/httpRefs.json
Fix for issue #563. Made fields lower camel case.
Thanks
> Class fields are now created to be lower camel case. Added interation test.

- jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java
Tiniest of tiny documentation fix for the maven plugin.
> Fix @since for useBigDecimals (TODO -> 0.4.22)

- jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy
> Issue #624: Default value of propertyWordDelimiters is empty in gradle vs "- _" for maven

- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/DefaultRule.java
- jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/DefaultIT.java
- jsonschema2pojo-integration-tests/src/test/resources/schema/default/default.json
> Support URI format properties with a default value using URI.create

- jsonschema2pojo-ant/src/main/java/org/jsonschema2pojo/ant/Jsonschema2PojoTask.java
- jsonschema2pojo-ant/src/site/Jsonschema2PojoTask.html
- jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
- jsonschema2pojo-cli/src/test/java/org/jsonschema2pojo/cli/ArgumentsTest.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/DefaultGenerationConfig.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/InclusionLevel.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Jackson1Annotator.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Jackson2Annotator.java
- jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/JsonSchemaExtension.groovy
- jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/InclusionLevelIT.java
- jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java
Hi, I have implemented option to set the "inclusion level" for jackson1 and jackson2 serializers, works in ant, cli, gradle and maven. Has integration tests.
> Jackson inclusion option

- resources/public/index.html
> Add initializeCollections option to jsonschema2pojo.org UI

- jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/GenerateJsonSchemaJavaTask.groovy
detect configuration changes in jsonschema2pojo gradle configuration
> detect configuration changes: issue #744

- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/model/EnumDefinition.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/model/EnumDefinitionExtensionType.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/model/EnumValueDefinition.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/EnumRule.java
Replace writing to Standard Out/Err to loggers.
Add some javadocs.
Adds copy constructors for EnumDefinition/EnumValueDefinition
> Add loggers to enum rule and improvements 

- jsonschema2pojo-gradle-plugin/example/android/lib/build.gradle
I found some obsolete and misleading left-overs.
CI test also performs well 😉
> Cleanup Android sample

- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/DefaultRule.java
- jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/rules/DefaultRuleTest.java
> Fix unnecessary initialization of Collection fields to "null"

- jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/RegressionIT.java
- jsonschema2pojo-integration-tests/src/test/resources/schema/regression/extends_in_array/flower.json
- jsonschema2pojo-integration-tests/src/test/resources/schema/regression/extends_in_array/flowerarray.json
> Regression test for support of 'extends' in array item type

- jsonschema2pojo-cli/pom.xml
- jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
- jsonschema2pojo-cli/src/main/resources/org/jsonschema2pojo/cli/version.properties
- jsonschema2pojo-cli/src/test/java/org/jsonschema2pojo/cli/ArgumentsTest.java
- pom.xml
> Add command line option to print version

- jsonschema2pojo-cli/src/main/java/org/jsonschema2pojo/cli/Arguments.java
- jsonschema2pojo-cli/src/test/java/org/jsonschema2pojo/cli/ArgumentsTest.java
> Accept multiple values provided with single "-s"/"--source" argument

- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/SchemaMapper.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ArrayRule.java
- jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/ref/SelfRefIT.java
- jsonschema2pojo-integration-tests/src/test/resources/schema/ref/selfReferencingArrayItem.json
> Use generated item type for array item if it is present

- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/Jsonschema2Pojo.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/NoopRuleLogger.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/SchemaStore.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/EnumRule.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/RuleFactory.java
- jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/GenerateJsonSchemaAndroidTask.groovy
- jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/GenerateJsonSchemaJavaTask.groovy
- jsonschema2pojo-intellij-formatter.xml
> Add useful debug logging when reading schemas and creating classes

- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/DefaultGenerationConfig.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/GenerationConfig.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/EnumRule.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/ObjectRule.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/AnnotationHelper.java
- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/JavaVersion.java
- jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/util/JavaVersionTest.java
- jsonschema2pojo-gradle-plugin/README.md
- jsonschema2pojo-integration-tests/pom.xml
- jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/config/IncludeGeneratedAnnotationIT.java
- jsonschema2pojo-maven-plugin/src/main/java/org/jsonschema2pojo/maven/Jsonschema2PojoMojo.java
Closes #1474, closes #1473, closes #1361
> Use targetVersion to decide which Generated annotation to add

- .github/workflows/ci.yml
Switch CI job runner to 'ubuntu-latest'
* Use identical runner value across all workflows
> Switch CI job runner to 'ubuntu-latest'

- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/JsonPointerUtils.java
- jsonschema2pojo-core/src/test/java/org/jsonschema2pojo/JsonPointerUtilsTest.java
- jsonschema2pojo-integration-tests/src/test/java/org/jsonschema2pojo/integration/PropertiesIT.java
- jsonschema2pojo-integration-tests/src/test/resources/schema/properties/propertiesWithSpecialCharacters.json
> Add support for property names containing question mark(s)

- jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/rules/EnumRule.java
> Don't log ClassAlreadyExistsException for Enum

- jsonschema2pojo-gradle-plugin/src/main/groovy/org/jsonschema2pojo/gradle/GenerateJsonSchemaJavaTask.groovy
> Retrieve sourceCompatibility directly from instance class instead of meta properties field
